services:
  app:
    image: image_name:tagname #replace with the correct tag
    restart: always
    environment:
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXTAUTH_URL=${NEXTAUTH_URL}
    ports:
      - '3000:3000'
    networks:
      - dalgo-network
    extra_hosts:
      - 'host.docker.internal:host-gateway'

networks:
  dalgo-network:
    driver: bridge
