name: Deploy code

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: main

      - name: Create known_hosts file
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts

      - name: Add remote host to known_hosts
        run: ssh-keyscan ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Connect to server
        run: |
          eval `ssh-agent`
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}

      - name: Pull the code and build
        run: |
          cd ${{ secrets.WEBAPP_WORKDIR }} 
          git pull
          pm2 stop prefect-agent
          yarn build
          pm2 start prefect-agent
          pm2 restart ddp-webapp
