name: Dalgo CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy code to EC2 server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          command_timeout: 500s
          script: |
            set -e
            source ~/.nvm/nvm.sh
            cd /home/ddp/webapp
            current_branch=$(git rev-parse --abbrev-ref HEAD)
            if [ "$current_branch" != "main" ]; then
              echo "Error: You are not on the main branch. Current branch is $current_branch."
              exit 1
            fi
            git pull
            yarn install
            yarn build
            /home/ddp/.yarn/bin/pm2 restart ddp-webapp
